/**********************************************************************
 * Regression and stability estimation.
 * Copyright (C) 2013  Georg Rudoy
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 **********************************************************************/

#pragma once

#include <iammad/parse.h>
#include <iammad/params.h>
#include "defs.h"

namespace Models
{
class Series
{
public:
	static constexpr size_t ParamsCount = 3;

	static std::array<DType_t, ParamsCount> initial ();

	static DType_t residual (const std::pair<SampleType_t<>, DType_t>& data, const Params_t<ParamsCount>& p);

	static Params_t<ParamsCount> residualDer (const std::pair<SampleType_t<>, DType_t>& data, const Params_t<ParamsCount>& p);

	static SampleType_t<> varsDer (const std::pair<SampleType_t<>, DType_t>& data, const Params_t<ParamsCount>& p);

	static TrainingSet_t<> preprocess (const TrainingSet_t<>& srcPts);
};

namespace LaserDetail
{
	using namespace Parse;

	constexpr auto g0 = w0;
	constexpr auto alpha0 = w1;
	constexpr auto k = w2;
	constexpr auto r0 = x0;
	constexpr auto logr0 = x1;
	constexpr auto r0ppsq = x2;
	constexpr auto r0recip = x3;

	using Formula_t = decltype (k * (_1 - r0) / (_1 + r0) * (g0 / (alpha0 - logr0 / Num<300>) - _1));

	using Unwrapped_t = ApplyDependency_t<decltype (logr0), decltype (Parse::Ln (r0)), Formula_t>;
	using VarsDerivative_t = Simplify::Simplify_t<VarDerivative_t<Unwrapped_t, decltype (r0)>>;
	using VarsCacheLog_t = ApplyDependency_t<decltype (Parse::Ln (r0)), decltype (logr0), VarsDerivative_t>;
	using VarsCachedSq_t = ApplyDependency_t<decltype ((-k * (_1 + r0) - (k * (_1 - r0))) / ((_1 + r0) * (_1 + r0))), decltype (k * r0ppsq), VarsCacheLog_t>;
	using VarsCachedRecip_t = ApplyDependency_t<decltype (k * (_1 - r0) / (_1 + r0)), decltype (k * r0recip), VarsCachedSq_t>;

	using VarsDer_t = VarsCachedRecip_t;
}

class Laser
{
	static constexpr auto L = 300.0;
public:
	static constexpr size_t ParamsCount = 3;

	static constexpr size_t IndependentCount = 4;

	using Formula_t = LaserDetail::Formula_t;
	using VarsDer_t = LaserDetail::VarsDer_t;

	template<typename DataVec, typename ParamsVec>
	static auto BindParams (const DataVec& data, const ParamsVec& p)
	{
		return Params::BuildFunctor<DType_t> (LaserDetail::g0, p (0),
				LaserDetail::alpha0, p (1),
				LaserDetail::k, p (2),
				LaserDetail::r0ppsq, data (2),
				LaserDetail::r0recip, data (3),
				LaserDetail::r0, data (0),
				LaserDetail::logr0, data (1));
	}

	static std::array<DType_t, ParamsCount> initial ();

	static DType_t residual (const std::pair<SampleType_t<IndependentCount>, DType_t>& data, const Params_t<ParamsCount>& p);

	static Params_t<ParamsCount> residualDer (const std::pair<SampleType_t<IndependentCount>, DType_t>& data, const Params_t<ParamsCount>& p);

	static SampleType_t<> varsDer (const std::pair<SampleType_t<IndependentCount>, DType_t>& data, const Params_t<ParamsCount>& p);

	static TrainingSet_t<IndependentCount> preprocess (const TrainingSet_t<>& srcPts);
};

class Resonance
{
public:
	static constexpr size_t ParamsCount = 3;

	DType_t residual (const std::pair<SampleType_t<>, DType_t>& data, const Params_t<ParamsCount>& p);

	Params_t<ParamsCount> residualDer (const std::pair<SampleType_t<>, DType_t>& data, const Params_t<ParamsCount>& p);
};
}
